
# Site
title: Simples Crentes

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://simplescrentes.org
root: /
permalink: :slug/
permalink_defaults:
  slug: :title

# Writing
post_asset_folder: false

# Date / Time format
date_format: YYYY/MM/DD
time_format: HH:mm:ss

# Extensions
theme: custom

# Deployment
deploy:
  type:
