
# Site
title: Simples Crentes

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://simplescrentes.org
root: /
permalink: :slug/
permalink_defaults:
  slug: :title

# Writing
post_asset_folder: false

# Date / Time format
date_format: YYYY/MM/DD
time_format: HH:mm:ss

# Extensions
theme: custom

# Deployment
deploy:
  type:

# Editor
prose:
  rooturl: 'source/_posts'
  siteurl: 'http://simplescrentes.org'
  ignore:
    - /_prose.yml
    - /_config.yml
    - /.editorconfig
    - /.gitignore
    - /.jshintrc
    - /package.json
    - /node_modules
  metadata:
    source/posts:
      - name: "title"
        field:
          element: "text"
          label: "Título"
          placeholder: "Título"
          alterable: true
      - name: "registro"
        field:
          element: "text"
          label: "Código de Registro"
          placeholder: "Código"
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Data, no formato: YYYY-MM-DD HH:MM:SS"
          value: "CURRENT_DATETIME"
      - name: "published"
        field:
          element: "checkbox"
          label: "Publicado"
          value: false
